version: '3'
services:
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: devstore-rabbitmq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: "devstore"
  #     RABBITMQ_DEFAULT_PASS: "devstore"
  #   expose:
  #     - 5672
  #   ports:
  #     - 15672:15672
  #     - 5672:5672
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: devstore-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: devstore-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: devstore-kafdrop
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: devstore-sqlserver
    environment:
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    expose:
      - 1433
    ports:
      - 1433:1433
  seq:
    image: datalust/seq:latest
    container_name: devstore-seq
    environment:
      ACCEPT_EULA: "Y"
    expose:
      - 5341
    ports:
      - 5341:5341
      - 80:80